language: rust
cache: cargo
script:
- |
  cd rust
  cargo test --release
  cd ..
  python2 --version
  pip2 --version
  pip2 install --user --upgrade pip setuptools wheel
  python2 setup.py bdist_wheel
  pip2 install --user pytest hypothesis mock jinja2
  python2 setup.py test
rust: nightly
jobs:
  include:
  - os: linux
    stage: test
  - os: osx
    stage: test
stages:
- name: test
deploy:
- provider: s3
  access_key_id: AKIAJRSWHGVBJUV5HFZA
  skip_cleanup: true
  secret_access_key:
    secure: ad4XAqhjXOD879rJesZtNTMmor8qqRbu8gvLkw2mh4mvpQjy37Mz8ciqVISDa467q7aHPw3vATAXOpKCpasuycSm3eyayYP0Zw/pDCnvhWg+Fe7n8LrA1JE9xuQMMyNfP5XG0Apqx+3atzlKP4jbIKTuM0QxJOkaW1UjFikPWSijQkL49219dVxHmMmshsjebQApWeFpfgS1FmuWNWFW9V9+gZjenfwqm3aS6bTCCGpKqUsgg1reS/ZtpkJDgRgcxp6UuFPdKmjn3kYWg7DJ884VEqMzWPnKur1yubAtFHAMhAHVXqZKg2Y7Lxk4ILz527OMIrq6FdOPPj7Bn0PODi3t/nW+7EdL+1DhvtzbKL9TzlQ+zw2ASa5i91OMCskH4Oty28cqmqB6mjBhu36Q8BLQ2kwGUqC8+W2d7Dozo862VqVLHUFx4E1v6stz0lABFx/wjPTnoOZXxLUZIxssnziwM8ItgrGIqbjg57PvLGnpOwf0VQhhsskmIXl88A8pxfrsvds5l3jq2FhBxSVu7VMukGmeiIcXTttCjoD7pdTbxH4Zp9ydvNNpTgVN+qVhf45BxZ5szKnFIirJ54yoVmnmVx8sm/ixzP0sHDV/UQPIPwejiCXUJwW2ds69cfaqYrsrKiwg0FVW5cS8y9UDA8pDe3bu980kaLBiSo2fwJA=
  bucket: mbed-os
  local-dir: dist
  upload-dir: builds/cmsis-pack-manager/dist
  acl: public_read
  on:
    repo: ARMmbed/cmsis-pack-manager
    tags: true
- provider: releases
  api_key:
      secure: "mz4SUvEDvg1aXz22mLcGa7wDMn0g6U/7VJE5v0rtcaNgwL9J09eq15qDJrAaF038Jb/mbxh617b7j2KzRe+WO1mNYhjq9Js71khVFSKsFlYIjbVUlJmSmu5VmLtQ8MoHYwj5EZVtnTJP30SYE84e3d2ZN2RyjRKOtn/bL5I0XXiBm041v8MfrM/Jtwme8fQ875LDJ+EPW3xGzzCfUmSfnMs7dBYtvXW0cf+VqwCRpd4Es+ATWRB1Z2i+5rC34FpDzldi81RkjBVOmuDlrK2E1yg7KnS8EN6bRld8T/Av3oAXBewVvA8yJFIWS2mHbPTaGxCcDpUdDjynVQJ6b8X4fcl44FS8avG0Pg4doVhXMwqgmb5ViL9Yb8kXlEQndT8c0l5TWJ+ASl9UMFQUVU+lp0dP66dplOUaB/eTIct+7CuhQYMQQ/XDcYRSI0KdURp0hMIelcEp2i3NNcHJA6MdEd9yD7LU+Q4O3TVFYG9aLgMmFvdK2ufAXK4mPqkuzrM7lSVKOMG4hXJGSXpMplojflxmr908FRF0gXzSMqlTRiPMgCBU9wAn1597danY+rIwxeE9nvYSDa940fEHGvG0OzY5UFcy3ghvhZuo22cwQMyzyb/8PuYypaJcwp9/uAgB6ykrH/zzMU6MnPw1eDm4WQrlv9y+N3HXrW2tQCb2Mjw="
  skip_cleanup: true
  file_glob: true
  file: dist/*.whl
  on:
      tags: true
