[package]
name = "cmsis-pack-manager"
version = "0.1.0"
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]

[dependencies]
minidom = "*"
quick-xml = "*"
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"

[dependencies-dev]
time = "*"