restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
deps_key: &DEPS_KEY
  key: deps-1.19.0-{{ checksum "Cargo.lock" }}-{{ checksum "~/lib_key" }}-2
restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY
save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
    - target
    - /usr/local/cargo/registry/cache

job: &JOB
  working_directory: ~/build
  docker:
  - image: tomastomecek/rust:clippy
  steps:
  - checkout
  - run: apt-get update
  - run: apt-get install pkg-config libssl-dev
  - <<: *RESTORE_REGISTRY
  - run: cargo generate-lockfile
  - <<: *SAVE_REGISTRY
  - run: echo "${LIBRARY}-${VERSION}-${TARGET}" > ~/lib_key
  - <<: *RESTORE_DEPS
  - run: cargo run --target $TARGET
  - run: |
      ulimit -c unlimited
      cargo test \
        --target $TARGET \
        --all-features \
  - store_artifacts:
      path: /tmp/core_dumps
  - <<: *SAVE_DEPS

x86_64: &X86_64
  TARGET: x86_64-unknown-linux-gnu

base: &BASE
  RUST_BACKTRACE: 1

version: 2
jobs:
  x86_64:
    <<: *JOB
    environment:
      <<: [*X86_64, *BASE]
workflows:
  version: 2
  tests:
    jobs:
    - x86_64