[package]
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]
name = "cmsis-pack"
version = "0.2.0"

[dependencies]
failure = "0.1.1"
futures = "0.1.25"
minidom = "0.6.0"
quick-xml = "0.9.0"
rustc-demangle = "=0.1.13"
serde = "^1.0.89"
serde_derive = "^1.0.89"
serde_json = "1.0"
slog = "^2"
slog-term = "^2"
slog-async = "^2"
tokio-core = "0.1.17"
reqwest = { version = "0.9.21", default_features = false, features = ["rustls-tls"]}

[dev-dependencies]
time = "*"
