[package]
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>",
           "Chris Reed <chris.reed@arm.com>",
           "Mathias Brossard <mathias.brossard@arm.com>"]
name = "cmsis-pack"
version = "0.2.0"
edition = "2018"
description = "Rust crate for managing CMSIS PACKs"
license = "Apache-2.0"
categories = ["embedded", "hardware-support", "development-tools::debugging"]
keywords = ["embedded", "cmsis"]

[dependencies]
failure = "0.1.1"
futures = "0.1.29"
log = "0.4.8"
minidom = "^0.7.0"
quick-xml = "^0.10.0"
rustc-demangle = "0.1.16"
serde = "^1.0.89"
serde_derive = "^1.0.89"
serde_json = "1.0"
tokio-core = "0.1.17"
reqwest = { version = "0.9.24", default_features = false, features = ["rustls-tls"] }

[dev-dependencies]
time = "*"

[features]
default = []
