[package]
name = "cmsis"
version = "0.1.0"
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]

[dependencies]
error-chain = "0.10.0"
slog = "^2"
slog-term = "^2"
slog-async = "^2"
clap = "2.19.0"
app_dirs = {git = "https://github.com/theotherjimmy/app-dirs-rs.git", branch = "fix-nightly-1-29"}
pack-index = { path = "pack-index" }
pdsc = { path = "pdsc" }
utils = { path = "utils" }
cmsis-cffi = { path = "cmsis-cffi", optional = true }

[build-dependencies]
cbindgen = "0.1"

[dev-dependencies]
time = "*"

[profile.release]
debug = true

[workspace]

[features]
cffi = ["cmsis-cffi"]