[package]
name = "cmsis-cffi"
version = "0.1.0"
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]
build = "build.rs"

[lib]
name = "cmsis_cffi"
crate-type = ["cdylib"]

[dependencies]
slog = "^2"
slog-term = "^2"
slog-async = "^2"
pack-index = { path = "../pack-index" }

[build-dependencies]
cbindgen = "0.1"