[package]
name = "cmsis-cffi"
version = "0.2.0"
authors = ["Jimmy Brisson <theotherjimmy@gmail.com>"]

[lib]
name = "cmsis_cffi"
crate-type = ["cdylib"]

[dependencies]
slog = "^2"
slog-term = "^2"
slog-async = "^2"
failure = "0.1.1"
cmsis = { path = "../cmsis" }
