name: CI Build Wheel Windows
on: workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    env:
      CIBW_ARCHS_MACOS: x86_64 universal2
      CIBW_ARCHS_LINUX: auto aarch64
      CIBW_SKIP: "cp27-* cp34-* cp35-* cp36-* pp* *-win32"
      # CIBW_ENVIRONMENT: 'PATH="$PATH:/usr/share/rust/.cargo/bin:$HOME/.cargo/bin"'
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y && yum install -y openssl-devel"
      CIBW_BEFORE_BUILD: "python -m pip install --upgrade pip wheel setuptools"
      RUSTFLAGS: "-Ctarget-feature=+crt-static"

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0          

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
