name: Continuous Integration
on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
    name: "${{ matrix.python-version }}"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # TODO: 'architecture' defaults to x64, invetigate x86 option
      - name: Cache Python modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          rm -rf .cache .eggs rust_fst/_ffi.py build *.egg-info
          find ./ -name "__pycache__" -type d -print0 |xargs -0 rm -rf
          find ./ -name "*.pyc" -type f -print0 |xargs -0 rm -rf
          find ./ -name "*.so" -type f -print0 |xargs -0 rm -rf
          pip install -U setuptools pip
          pip install -U --upgrade-strategy=eager -r requirements.txt
          pip install -U --upgrade-strategy=eager -r setup_requirements.txt
          pip install -U --upgrade-strategy=eager -r test_requirements.txt   
          sudo apt install libffi-dev
      - name: Compile
        run: |
          python setup.py build
          python setup.py install
      - name: Run Tests
        run: |
          pytest --cache-clear
